spring:

  datasource:
    platform: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: capitaltrackerdb
    url: "jdbc:mysql://localhost:3306/capitaltrackerdb?autoReconnect=true"
    username: root
    password: root

    initialize: true
    initialization-mode: always

  jpa:
    show-sql: true
    hibernate.ddl-auto: none